var VelvetConstants = {
	LOADING_NUMBERS: "LOADING_NUMBERS",
	LOADING_NUMBERS_SUCCESS: "LOADING_NUMBERS_SUCCESS",
	LOADING_NUMBERS_FAILURE: "LOADING_NUMBERS_FAILURE",
	LOADING_NUMBERS_INTERNAL: "LOADING_NUMBERS_INTERNAL",
	LOADING_NUMBERS_INTERNAL_SUCCESS: "LOADING_NUMBERS_INTERNAL_SUCCESS",
	LOADING_NUMBERS_INTERNAL_FAILURE: "LOADING_NUMBERS_INTERNAL_FAILURE",
	NEW_MESSAGE: "NEW_MESSAGE",
	NEW_NAME: "NEW_NAME",
	NUMBER_CHOSEN: "NUMBER_CHOSEN",

	LOADING_MESSAGES: "LOADING_MESSAGES",
	LOADING_MESSAGES_SUCCESS: "LOADING_MESSAGES_SUCCESS",
	LOADING_MESSAGES_FAILURE: "LOADING_MESSAGES_FAILURE",
	LOADING_SEND_REPLY: "LOADING_SEND_REPLY",
	LOADING_SEND_REPLY_SUCCESS: "LOADING_SEND_REPLY_SUCCESS",
	LOADING_SEND_REPLY_FAILURE: "LOADING_SEND_REPLY_FAILURE",
	LOADING_SET_NAME: "LOADING_SET_NAME",
	LOADING_SET_NAME_SUCCESS: "LOADING_SET_NAME_SUCCESS",
	LOADING_SET_NAME_FAILURE: "LOADING_SET_NAME_FAILURE",
	LOADING_SEND_RECEIPT: "LOADING_SEND_RECEIPT",
	LOADING_SEND_RECEIPT_SUCCESS: "LOADING_SEND_RECEIPT_SUCCESS",
	LOADING_SEND_RECEIPT_FAILURE: "LOADING_SEND_RECEIPT_FAILURE",
	TOGGLE_SEND_RECEIPT: "TOGGLE_SEND_RECEIPT",
	LOADING_GET_MEDICAL_PROFILE_TOKEN: "LOADING_GET_MEDICAL_PROFILE_TOKEN",
	LOADING_GET_MEDICAL_PROFILE_TOKEN_SUCCESS: "LOADING_GET_MEDICAL_PROFILE_TOKEN_SUCCESS",
	LOADING_GET_MEDICAL_PROFILE_TOKEN_FAILURE: "LOADING_GET_MEDICAL_PROFILE_TOKEN_FAILURE",
	CLOSE_GET_MEDICAL_PROFILE_TOKEN_MODAL: "CLOSE_GET_MEDICAL_PROFILE_TOKEN_MODAL",

	SESSION_CHECK_LOADING: "SESSION_CHECK_LOADING",
	SESSION_CHECK_SUCCESS: "SESSION_CHECK_SUCCESS",
	SESSION_CHECK_ERROR: "SESSION_CHECK_ERROR",
	SESSION_TIMEOUT: "SESSION_TIMEOUT",
	LOGIN_LOADING: "LOGIN_LOADING",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_ERROR: "LOGIN_ERROR"
};

module.exports = VelvetConstants;